genres:
  - name: "ラーメン"
  - name: "つけ麺"
  - name: "油そば"

noodles:
  - name: "細麺"
  - name: "太麺"
  - name: "中太麺"
  - name: "ちぢれ麺"

soups:
  - name: "醤油"
  - name: "味噌"
  - name: "塩"
  - name: "豚骨"
  - name: "魚介"
  - name: "鶏白湯"
  - name: "担々麺"
  - name: "家系"
  - name: "二郎系"
  - name: "ベジポタ"

shops:
  - name: "ラーメン荘 歴史を刻め 世田谷"
  - name: "中華そば みやざき"

menus:
  - shop: "ラーメン荘 歴史を刻め 世田谷"
    name: "ラーメン"
    genre: "ラーメン"
    noodle: "太麺"
    soup: "二郎系"
  - shop: "ラーメン荘 歴史を刻め 世田谷"
    name: "汁なし"
    genre: "油そば"
    noodle: "太麺"
    soup: "二郎系"
  - shop: "中華そば みやざき"
    name: "中華そば"
    genre: "ラーメン"
    noodle: "細麺"
    soup: "醤油"
  - shop: "中華そば みやざき"
    name: "濃厚鯖つけ麺"
    genre: "つけ麺"
    noodle: "太麺"
    soup: "煮干し"
