# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - "node_modules/**/*"
  NewCops: enable

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['\A#']
  Exclude:
    - "db/migrate/*.rb"

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
