name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '.tool-versions'
          bundler-cache: true

      - name: Run RuboCop
        run: |
          bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '.tool-versions'
          bundler-cache: true

      - name: Set up database
        run: |
          bin/rails db:prepare

      - name: Run RSpec
        run: |
          bundle exec rspec
